require: rubocop-rails

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Exclude:
    - app/models/booking.rb
    - app/models/user.rb
    - app/jobs/booking_notification_job.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/booking.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/models/booking.rb

Metrics/BlockLength:
  Exclude:
    - spec/requests/categories_spec.rb
    - spec/routing/categories_routing_spec.rb

Rails/FilePath:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
